### ISSUE TITLE
Update projects that depend on tiny-lr

### ISSUE THREAD

**Issue by elwayman02** [elwayman02/mini-lr#4]
- [ ] [angular2-seed](https://github.com/mgechev/angular2-seed) - [Issue](https://github.com/mgechev/angular2-seed/issues/89) - [Pull Request](https://github.com/mgechev/angular2-seed/pull/91)
- [ ] [budo](https://github.com/mattdesl/budo) - [Pull Request](https://github.com/mattdesl/budo/pull/74)
- [ ] [driven-cli](https://github.com/Appyre/driven-cli) - [Pull Request](https://github.com/Appyre/driven-cli/pull/1)
- [x] [ember-cli](https://github.com/ember-cli/ember-cli) - [Issue](https://github.com/ember-cli/ember-cli/issues/4896) - [Pull Request](https://github.com/ember-cli/ember-cli/pull/4897)
- [ ] [grunt-contrib-watch](https://github.com/gruntjs/grunt-contrib-watch#live-reloading) - [Pull Request](https://github.com/gruntjs/grunt-contrib-watch/pull/462)
- [x] [gulp-livereload](https://github.com/vohof/gulp-livereload) - [Issue](https://github.com/vohof/gulp-livereload/issues/94) - [Pull Request](https://github.com/vohof/gulp-livereload/pull/97)
- [ ] [gulp-mock-server](https://github.com/sanyueyu/gulp-mock-server) - [Pull Request](https://github.com/sanyueyu/gulp-mock-server/pull/1)
- [ ] [make-livereload](https://github.com/mklabs/make-livereload) via #2 
- [ ] [superstatic](https://github.com/divshot/superstatic) - [Pull Request](https://github.com/divshot/superstatic/pull/176)
- [ ] [vtex toolbelt](https://github.com/vtex/toolbelt) - [Issue](https://github.com/vtex/toolbelt/issues/53)
- [ ] [webpack-livereload-plugin](https://github.com/statianzo/webpack-livereload-plugin) - [Pull Request](https://github.com/statianzo/webpack-livereload-plugin/pull/7)

[Other Projects](https://www.npmjs.com/browse/depended/tiny-lr)
